Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/azureuser/consultant-matchmaker-v2/venv/lib/python3.10/site-packages/uvicorn/__main__.py", line 4, in <module>
    uvicorn.main()
  File "/home/azureuser/consultant-matchmaker-v2/venv/lib/python3.10/site-packages/click/core.py", line 1442, in __call__
    return self.main(*args, **kwargs)
  File "/home/azureuser/consultant-matchmaker-v2/venv/lib/python3.10/site-packages/click/core.py", line 1363, in main
    rv = self.invoke(ctx)
  File "/home/azureuser/consultant-matchmaker-v2/venv/lib/python3.10/site-packages/click/core.py", line 1226, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/azureuser/consultant-matchmaker-v2/venv/lib/python3.10/site-packages/click/core.py", line 794, in invoke
    return callback(*args, **kwargs)
  File "/home/azureuser/consultant-matchmaker-v2/venv/lib/python3.10/site-packages/uvicorn/main.py", line 416, in main
    run(
  File "/home/azureuser/consultant-matchmaker-v2/venv/lib/python3.10/site-packages/uvicorn/main.py", line 587, in run
    server.run()
  File "/home/azureuser/consultant-matchmaker-v2/venv/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/home/azureuser/consultant-matchmaker-v2/venv/lib/python3.10/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/azureuser/consultant-matchmaker-v2/venv/lib/python3.10/site-packages/uvicorn/config.py", line 467, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/azureuser/consultant-matchmaker-v2/venv/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/azureuser/consultant-matchmaker-v2/app/main.py", line 18, in <module>
    from app.services.cv_processor import cv_processor
  File "/home/azureuser/consultant-matchmaker-v2/app/services/cv_processor.py", line 18, in <module>
    class CVProcessor:
  File "/home/azureuser/consultant-matchmaker-v2/app/services/cv_processor.py", line 319, in CVProcessor
    def get_supported_extensions(self) -> List[str]:
NameError: name 'List' is not defined. Did you mean: 'list'?
